# Generated by Django 3.2.5 on 2021-07-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_administrador_categoria_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='nombre_completo',
            field=models.CharField(max_length=90),
        ),
    ]
